name: Test action inputs
on:
  push:
    branches: ["test"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Inject secrets to yaml files
        uses: none0nfg/yaml-secrets-injector@v0.0.1-test
        with:
          inject_files: |-
            [
              "path/to/file1.yaml",
              "path/to/file2.yaml"
            ]
          secrets: ${{ toJSON(secrets) }}